### PR TITLE
Fixes to packaging

### PR DESCRIPTION
**Pull request by nphilipp**

### CODE REVIEW

**Comment by sgallagher** [comment]
Looks like it's failing the coverage check across the board. We should either disable that or add tests (which I realize may be difficult for the plugin here).

**Comment by nphilipp** [comment]
> Looks like it's failing the coverage check across the board. We should either disable that or add tests (which I realize may be difficult for the plugin here).

The coverage is low because of the tests which fail because the `koji` package isn’t available:

```
 E   ModuleNotFoundError: No module named 'koji'
```

I’m on it.

**Comment by sgallagher** [comment]
The ci-smoketests pipeline needs `krb5-devel` to install `koji` properly.

**Comment by nphilipp** [comment]
> The ci-smoketests pipeline needs `krb5-devel` to install `koji` properly.

Hah, didn’t think of that this innocent change to tox.ini would affect the smoke tests, too:

```diff
@@ -5,7 +5,6 @@ isolated_build = true
 skip_missing_interpreters = true
 
 [testenv]
-skip_install = true
 sitepackages = false
 deps =
   pytest
```

**Pull request merged**
